#!/usr/bin/env php
<?php

// Load Dependency
require __DIR__.'/vendor/autoload.php';

// Settings
date_default_timezone_set('America/Los_Angeles');

// import the Symfony Console Application
use Symfony\Component\Console\Application;
use JoomlaBuildScript\Commands\JoomlaComponentCommand;

// Generate Console
$jextbuild = new Application;

$jextbuild->add(new JoomlaComponentCommand());

$jextbuild->run();
